- 1.1.4
- _NAME: Bluetooth Mouse M336/M337/M535
  _absent: [hi-res-scroll, lowres-smooth-scroll, smart-shift, thumb-scroll-mode, thumb-scroll-invert, report_rate, dpi, dpi-sliding, speed-change, backlight,
    fn-swap, disable-keyboard-keys, divert-crown, crown-smooth, divert-gkeys, multiplatform, change-host, gesture2-gestures, gesture2-params, onboard_profiles,
    backlight-timed, persistent-remappable-keys, m-key-leds, mr-key-led, gesture2-divert, lowres-scroll-mode]
  _modelId: B01600000000
  _sensitive: {hires-smooth-invert: ignore, hires-smooth-resolution: true, mouse-gestures: false}
  _serial: '00000000'
  _unitId: '00000000'
  _wpid: B01600000000
  divert-keys: {80: 0, 81: 0, 82: 0, 206: 0, 207: 0, 208: 1}
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  mouse-gestures: '208'
  pointer_speed: 256
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 206: 206, 207: 207, 208: 208}
- _NAME: G304 Lightspeed Wireless Gaming Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    report_rate, pointer_speed, dpi-sliding, speed-change, mouse-gestures, backlight, backlight-timed, fn-swap, reprogrammable-keys, persistent-remappable-keys,
    divert-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures,
    gesture2-divert, gesture2-params, sidetone, equalizer]
  _modelId: '407400000000'
  _serial: 5814AE93
  _unitId: 9C4CFB23
  _wpid: '4074'
  dpi: 800
  onboard_profiles: 1
- {_NAME: G304 Lightspeed Wireless Gaming Mouse, _modelId: '407400000000', _serial: 5814AE93, _unitId: 9C4CFB23, _wpid: '4074'}
